default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: graphql_blog_development

test:
  <<: *default
  database: graphql_blog_test

production:
  <<: *default
  database: graphql_blog_production
